env:
  global:
    - GIT_NAME: pelson
    # travis encrypt 'GIT_EMAIL=<email> GH_TOKEN=<token>'
    secure: "Xu67hAmd/oA/899DUg8PZOM1qR8Bir2p72A6E946MdMIi0gEF8s+lN/Ya/nx/7fveY8Wl8E6HbTRWVrMgfi1EY6MMnyi5k8kR/crroxdCV8FL+gT6iHr/2INAbRJT/aNMDMWm0KlzjfJTs/5R7OPP8YnIStQSsLV9DxXBCqfLk1o3O3Qf1uvQFWQiotYzz/NCeUVTD0Okjy7jtFu1ARIm7yOnddtin7hUpmpMIUlLGhcJb0ZyakVFWPN0lG+Vp1cU3o+a61zj6UidvN4H+NFL3LPY1izB5gy4ejJbYnkZrJnKbJ1Vv7v8G4Wu/oT5M2Q+Z5gNQmE00m1l9Ks1PUdXpmlZZuQSbHFqej/Tc5QjBoGFlTBrfCeurBuE70MyrnT3UxU0QYLHceD1M0WDsgp2FyHcaxP3nTE9Kh472iVl+WKCtSisLYNcQWfiPmMw4/qUnje9gJW3cCY5sdPvhaoVY1H9btVpAXBwbckJS/q677Rf8GAVfVUEfdy2N8gXwRT2kIJROrVSQ1Shtsat+btKZKaXuMHIFnSLXKoMRfnBAJ1tnljumtDoJKM8hTYGFPRgJtM6nDwcozoTho7/hRI/zjZCbESpAbPT7IknHUdib2fQFmSFltwvuXyiKoUIUwZg439Gp75Un1mEONWyZqJ7Nvx0MvoI13LFPsd6RGoxk8="
 
    - PYPI_USERNAME: pelson
    # Adds the $PYPI_PASSWORD. See http://docs.travis-ci.com/user/encryption-keys/.
    - secure: Znk+Ft7SFaQCCuoXLCWO9S91M9McHhgnDUnsyvT4znWXjAXAV9UgRW+lr5HmRekpovDJNf20VzzxOlq5zTOVibpWjFWV0AAuq1Bzy11KbnESTXs2vrwjGzo4JD2+AOHXKbC4B0jNcpITUjxtYDlchotJwyI1bzopQi0yVbUO7CR8QGBAsz+se8Hcb1jlNNr5EgvgTVxwXwyaxJZMhDMpRXmnR0e5U3pCSmDGuyKZJXpG+d72zxcHkZAFESkI1Nadu/4gkVVVYskQvgXzk1+oxNutze8FIGJ906Qllf7C7uf35C1nsCswI6IDUmk0KO5s3hAjHqS7r6+lXqj2rv1QyfBFvmW4Lu+0PFqOOY5mO2Lt7ieDsyHdGCBnni3CA73ULicPc9xd42RnIXTuL6JwKilgP8M9BY8tyUv8aIcfvXEV0Ak4bTe/aiPO2Rvg22sz6GFbleR+5XTnssY1o+Ovibl8HEbTCMg/nz5nhA66iX2nN9/ERPDIRo3YgCn5A653OSsnqYm52mYRx5nJR+C2DXyr8d+gU+fKIvNBzXu8zDqkUe3w2GEyhn1iSmOlWxxMEJ5vrf7sfiwfQw4ZP/trmhE6hnwWdh70ERgGkTFXguFR5R+FliXUtQz3poaE5CYkjDeRBpIUWWAYMnJ/B7XIIm5iNc/ro9ON+8+FHdEPhCU=
    
language: python

python:
 - '2.7'
 - '3.4'

install:
 - python setup.py install
 - python setup.py version

script: python -c "print('Tests should be done here.')"

after_success:
 - SHA=$(git rev-parse HEAD)
 - git remote add origin_auth https://${GIT_NAME}:${GH_TOKEN}@github.com/pelson/package_with_continuous_delivery.git
 - git fetch origin_auth _build && git checkout -b _build origin_auth/_build
 - git submodule update --init && git submodule status
 - cd package_with_continuous_delivery && git fetch && git status && git checkout $SHA && cd ..
 - git status
 - 'git -c user.name="${GIT_NAME}" -c user.email="${GIT_EMAIL}" commit -am "Travis ${TRAVIS_BUILD_NUMBER}: Update build branch to ${SHA}."'
 - git push origin_auth _build > /dev/null
