package:
    name: cd_example
    # Should come from the submodule
    version: 0.1

source:
    path: ../package_with_continuous_delivery
 
requirements:
    build:
        - python
        - numpy
    run:
        - python
        - numpy
